// Code generated by protoc-gen-go.
// source: token.proto
// DO NOT EDIT!

package igrpc

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type OfficialAccountPlatform struct {
	Appid                 string `protobuf:"bytes,1,opt,name=Appid" json:"Appid,omitempty"`
	ComponentVerifyTicket string `protobuf:"bytes,2,opt,name=ComponentVerifyTicket" json:"ComponentVerifyTicket,omitempty"`
	EncodingAesKey        string `protobuf:"bytes,3,opt,name=EncodingAesKey" json:"EncodingAesKey,omitempty"`
	AppSecret             string `protobuf:"bytes,4,opt,name=AppSecret" json:"AppSecret,omitempty"`
	ComponentAccessToken  string `protobuf:"bytes,5,opt,name=ComponentAccessToken" json:"ComponentAccessToken,omitempty"`
	PreAuthCode           string `protobuf:"bytes,6,opt,name=PreAuthCode" json:"PreAuthCode,omitempty"`
	Token                 string `protobuf:"bytes,7,opt,name=Token" json:"Token,omitempty"`
}

func (m *OfficialAccountPlatform) Reset()                    { *m = OfficialAccountPlatform{} }
func (m *OfficialAccountPlatform) String() string            { return proto.CompactTextString(m) }
func (*OfficialAccountPlatform) ProtoMessage()               {}
func (*OfficialAccountPlatform) Descriptor() ([]byte, []int) { return fileDescriptor11, []int{0} }

func (m *OfficialAccountPlatform) GetAppid() string {
	if m != nil {
		return m.Appid
	}
	return ""
}

func (m *OfficialAccountPlatform) GetComponentVerifyTicket() string {
	if m != nil {
		return m.ComponentVerifyTicket
	}
	return ""
}

func (m *OfficialAccountPlatform) GetEncodingAesKey() string {
	if m != nil {
		return m.EncodingAesKey
	}
	return ""
}

func (m *OfficialAccountPlatform) GetAppSecret() string {
	if m != nil {
		return m.AppSecret
	}
	return ""
}

func (m *OfficialAccountPlatform) GetComponentAccessToken() string {
	if m != nil {
		return m.ComponentAccessToken
	}
	return ""
}

func (m *OfficialAccountPlatform) GetPreAuthCode() string {
	if m != nil {
		return m.PreAuthCode
	}
	return ""
}

func (m *OfficialAccountPlatform) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type OfficialAccount struct {
	Appid                          string `protobuf:"bytes,1,opt,name=Appid" json:"Appid,omitempty"`
	AuthorizerAccessToken          string `protobuf:"bytes,2,opt,name=AuthorizerAccessToken" json:"AuthorizerAccessToken,omitempty"`
	AuthorizerAccessTokenExpiresIn int64  `protobuf:"varint,3,opt,name=AuthorizerAccessTokenExpiresIn" json:"AuthorizerAccessTokenExpiresIn,omitempty"`
	AuthorizerRefreshToken         string `protobuf:"bytes,4,opt,name=AuthorizerRefreshToken" json:"AuthorizerRefreshToken,omitempty"`
}

func (m *OfficialAccount) Reset()                    { *m = OfficialAccount{} }
func (m *OfficialAccount) String() string            { return proto.CompactTextString(m) }
func (*OfficialAccount) ProtoMessage()               {}
func (*OfficialAccount) Descriptor() ([]byte, []int) { return fileDescriptor11, []int{1} }

func (m *OfficialAccount) GetAppid() string {
	if m != nil {
		return m.Appid
	}
	return ""
}

func (m *OfficialAccount) GetAuthorizerAccessToken() string {
	if m != nil {
		return m.AuthorizerAccessToken
	}
	return ""
}

func (m *OfficialAccount) GetAuthorizerAccessTokenExpiresIn() int64 {
	if m != nil {
		return m.AuthorizerAccessTokenExpiresIn
	}
	return 0
}

func (m *OfficialAccount) GetAuthorizerRefreshToken() string {
	if m != nil {
		return m.AuthorizerRefreshToken
	}
	return ""
}

type ComponentVerifyTicket struct {
	TimeStamp string `protobuf:"bytes,1,opt,name=TimeStamp" json:"TimeStamp,omitempty"`
	Nonce     string `protobuf:"bytes,2,opt,name=Nonce" json:"Nonce,omitempty"`
	MsgSign   string `protobuf:"bytes,3,opt,name=MsgSign" json:"MsgSign,omitempty"`
	Bts       []byte `protobuf:"bytes,4,opt,name=bts,proto3" json:"bts,omitempty"`
}

func (m *ComponentVerifyTicket) Reset()                    { *m = ComponentVerifyTicket{} }
func (m *ComponentVerifyTicket) String() string            { return proto.CompactTextString(m) }
func (*ComponentVerifyTicket) ProtoMessage()               {}
func (*ComponentVerifyTicket) Descriptor() ([]byte, []int) { return fileDescriptor11, []int{2} }

func (m *ComponentVerifyTicket) GetTimeStamp() string {
	if m != nil {
		return m.TimeStamp
	}
	return ""
}

func (m *ComponentVerifyTicket) GetNonce() string {
	if m != nil {
		return m.Nonce
	}
	return ""
}

func (m *ComponentVerifyTicket) GetMsgSign() string {
	if m != nil {
		return m.MsgSign
	}
	return ""
}

func (m *ComponentVerifyTicket) GetBts() []byte {
	if m != nil {
		return m.Bts
	}
	return nil
}

func init() {
	proto.RegisterType((*OfficialAccountPlatform)(nil), "igrpc.OfficialAccountPlatform")
	proto.RegisterType((*OfficialAccount)(nil), "igrpc.OfficialAccount")
	proto.RegisterType((*ComponentVerifyTicket)(nil), "igrpc.ComponentVerifyTicket")
}

func init() { proto.RegisterFile("token.proto", fileDescriptor11) }

var fileDescriptor11 = []byte{
	// 328 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x84, 0x52, 0xcd, 0x4e, 0x32, 0x31,
	0x14, 0x0d, 0xf0, 0x01, 0xe1, 0xf2, 0x45, 0x4d, 0x83, 0xda, 0x85, 0x31, 0x84, 0x85, 0x71, 0xe5,
	0x42, 0x8d, 0xfb, 0x86, 0x60, 0x62, 0x8c, 0x4a, 0x06, 0xe2, 0x1e, 0xca, 0x9d, 0xa1, 0x81, 0x69,
	0x9b, 0xb6, 0x44, 0xf1, 0x45, 0x7c, 0x3a, 0xdf, 0xc5, 0xb4, 0x1d, 0x85, 0x90, 0x21, 0xee, 0xe6,
	0xfc, 0xe4, 0xce, 0x3d, 0xe7, 0x16, 0xda, 0x4e, 0x2d, 0x50, 0x5e, 0x69, 0xa3, 0x9c, 0x22, 0x75,
	0x91, 0x19, 0xcd, 0x7b, 0x9f, 0x55, 0x38, 0x7d, 0x49, 0x53, 0xc1, 0xc5, 0x64, 0xc9, 0x38, 0x57,
	0x2b, 0xe9, 0x86, 0xcb, 0x89, 0x4b, 0x95, 0xc9, 0x49, 0x07, 0xea, 0x4c, 0x6b, 0x31, 0xa3, 0x95,
	0x6e, 0xe5, 0xb2, 0x95, 0x44, 0x40, 0x6e, 0xe1, 0xb8, 0xaf, 0x72, 0xad, 0x24, 0x4a, 0xf7, 0x8a,
	0x46, 0xa4, 0xeb, 0xb1, 0xe0, 0x0b, 0x74, 0xb4, 0x1a, 0x5c, 0xe5, 0x22, 0xb9, 0x80, 0x83, 0x81,
	0xe4, 0x6a, 0x26, 0x64, 0xc6, 0xd0, 0x3e, 0xe2, 0x9a, 0xd6, 0x82, 0x7d, 0x87, 0x25, 0x67, 0xd0,
	0x62, 0x5a, 0x8f, 0x90, 0x1b, 0x74, 0xf4, 0x5f, 0xb0, 0x6c, 0x08, 0x72, 0x0d, 0x9d, 0xdf, 0xf1,
	0x8c, 0x73, 0xb4, 0x76, 0xec, 0x23, 0xd1, 0x7a, 0x30, 0x96, 0x6a, 0xa4, 0x0b, 0xed, 0xa1, 0x41,
	0xb6, 0x72, 0xf3, 0xbe, 0x9a, 0x21, 0x6d, 0x04, 0xeb, 0x36, 0xe5, 0x73, 0xc6, 0x31, 0xcd, 0x98,
	0x33, 0x80, 0xde, 0x57, 0x05, 0x0e, 0x77, 0x9a, 0xd9, 0xdf, 0x88, 0x9f, 0xa5, 0x8c, 0xf8, 0x40,
	0xb3, 0xbd, 0x56, 0xd1, 0x48, 0xa9, 0x48, 0xee, 0xe1, 0xbc, 0x54, 0x18, 0xbc, 0x6b, 0x61, 0xd0,
	0x3e, 0xc8, 0xd0, 0x50, 0x2d, 0xf9, 0xc3, 0x45, 0xee, 0xe0, 0x64, 0xe3, 0x48, 0x30, 0x35, 0x68,
	0xe7, 0xf1, 0xf7, 0xb1, 0xbe, 0x3d, 0x6a, 0xef, 0x6d, 0xcf, 0x1d, 0xfd, 0x09, 0xc6, 0x22, 0xc7,
	0x91, 0x9b, 0xe4, 0xba, 0x08, 0xba, 0x21, 0x7c, 0x05, 0xcf, 0x4a, 0x72, 0x2c, 0xc2, 0x45, 0x40,
	0x28, 0x34, 0x9f, 0x6c, 0x36, 0x12, 0x99, 0x2c, 0xee, 0xfa, 0x03, 0xc9, 0x11, 0xd4, 0xa6, 0xce,
	0x86, 0x5d, 0xfe, 0x27, 0xfe, 0x73, 0xda, 0x08, 0x0f, 0xf0, 0xe6, 0x3b, 0x00, 0x00, 0xff, 0xff,
	0xfe, 0x15, 0x24, 0xc6, 0x8f, 0x02, 0x00, 0x00,
}
